export const SET_GAME_STARTED = 'SET_GAME_STARTED';
export const SET_INSTRUCTIONS_EXPANDED = 'SET_INSTRUCTIONS_EXPANDED';
//export const FETCH_DECK_RESULT = 'FETCH_DECK_RESULT';
//export const FETCH_DECK_ERROR = 'FETCH_DECK_ERROR';

export const DECK = {
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_ERROR: 'FETCH_ERROR'
};